services:
  - type: web
    name: shriram-insurance
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/feedbacks
    envVars:
      - key: NODE_ENV
        value: production 